"""現場検証台帳の固定code。"""

from enum import StrEnum


class FieldMode(StrEnum):
    SHADOW = "SHADOW"
    ADVISORY = "ADVISORY"
    OPERATIONAL = "OPERATIONAL"


class OperatorDecision(StrEnum):
    OBSERVED = "OBSERVED"
    ACCEPTED = "ACCEPTED"
    INCREASED = "INCREASED"
    DECREASED = "DECREASED"
    REJECTED = "REJECTED"
    NO_ACTION = "NO_ACTION"


class OperatorReasonCode(StrEnum):
    PROMOTION = "PROMOTION"
    SEASONAL_EVENT = "SEASONAL_EVENT"
    CUSTOMER_INFORMATION = "CUSTOMER_INFORMATION"
    EXPECTED_LARGE_ORDER = "EXPECTED_LARGE_ORDER"
    PRODUCTION_CONSTRAINT = "PRODUCTION_CONSTRAINT"
    DELIVERY_CONSTRAINT = "DELIVERY_CONSTRAINT"
    EXPIRY_CONCERN = "EXPIRY_CONCERN"
    STOCKOUT_CONCERN = "STOCKOUT_CONCERN"
    WAREHOUSE_CAPACITY = "WAREHOUSE_CAPACITY"
    EXPERIENCE_JUDGMENT = "EXPERIENCE_JUDGMENT"
    DATA_ERROR = "DATA_ERROR"
    OTHER = "OTHER"
